name: Pylint

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '.gitignore'
      - '.prettierrc'
      - '**/*.svg'
      - '**/*.md'

permissions:
  contents: read

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      changed_dirs: ${{ steps.filter.outputs.changes }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit
    
    - id: filter
      uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
      with:
        filters: |
          compare_pdfs:
            - 'compare_pdfs/**'
            - '.github/workflows/pylint.yml'
          convert_intro_to_md:
            - 'convert_intro_to_md/**'
            - '.github/workflows/pylint.yml'
          convert_source_description:
            - 'convert_source_description/**'
            - '.github/workflows/pylint.yml'
          unify_ids:
            - 'unify_ids/**'
            - '.github/workflows/pylint.yml'

  lint:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.changed_dirs != '[]' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        dir: ${{ fromJSON(needs.detect_changes.outputs.changed_dirs) }}
    
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      working-directory: ${{ matrix.dir }}
      run: |
        python -m ensurepip --upgrade
        pip install --require-hashes -r ./requirements.txt
      
    - name: Analysing the code with pylint
      working-directory: ${{ matrix.dir }}
      run: |
        find . -name "*.py" -not -path "./.venv/*" | while read file; do
          echo "Running pylint on $file"
          pylint "$file" || exit 1
        done
