name: Pytest

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '.gitignore'
      - '.prettierrc'
      - '**/*.svg'
      - '**/*.md'

permissions:
  contents: read

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      changed_dirs: ${{ steps.filter.outputs.changes }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit
    
    - id: filter
      uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      with:
        filters: |
          convert_intro_to_md:
            - 'convert_intro_to_md/**'
            - '.github/workflows/pytest.yml'
          convert_source_description:
            - 'convert_source_description/**'
            - '.github/workflows/pytest.yml'
          unify_ids:
            - 'unify_ids/**'
            - '.github/workflows/pytest.yml'

  lint:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.changed_dirs != '[]' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        dir: ${{ fromJSON(needs.detect_changes.outputs.changed_dirs) }}
    
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      working-directory: ${{ matrix.dir }}
      run: |
        python -m ensurepip --upgrade
        pip install --require-hashes -r ./requirements.txt
      
    - name: Test the code with pytest
      working-directory: ${{ matrix.dir }}
      run: |
        pytest tests/ -v
